# Generated by Django 4.2.29 on 2026-06-18 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('delete', models.DateTimeField(blank=True, default=None, help_text='Date time on which the object was last delete.', null=True, verbose_name='delete at')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18)),
                ('cuenta_destino', models.CharField(max_length=100)),
                ('numero_cheque', models.CharField(max_length=45)),
                ('banco_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.banco')),
                ('cuenta_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.cuentabancaria')),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_transferencia', to='contabilidad.pagodocumento')),
                ('uc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('um', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_update', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
