# Generated by Django 4.2.29 on 2026-06-22 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_pagotransferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefacturas',
            name='documentos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_facturas', to='contabilidad.documentos'),
        ),
    ]
