# Generated by Django 4.2.29 on 2026-06-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_saldosnits_saldos'),
    ]

    operations = [
        migrations.AddField(
            model_name='mov',
            name='dcierre',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
