# Generated by Django 4.2.29 on 2026-06-22 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_alter_detallefacturas_documentos'),
        ('contabilidad', '0004_mov_dcierre'),
    ]

    operations = [
    ]
