# Generated by Django 4.2.29 on 2026-06-25 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_merge_20260622_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentos',
            name='mandato',
        ),
        migrations.RemoveField(
            model_name='historicaldocumentos',
            name='mandato',
        ),
        migrations.AlterField(
            model_name='documentos',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipodocumento_personas', to='contabilidad.tiposdocumentos'),
        ),
    ]
