# Generated by Django 4.2.29 on 2026-07-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_remove_documentos_mandato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRetencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'contabilidad_tipos_retenciones',
            },
        ),
    ]
