# Generated by Django 4.2.29 on 2026-07-15 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0008_cupon_historicalcupon_detallecupones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecupones',
            name='concepto',
        ),
        migrations.RemoveField(
            model_name='detallecupones',
            name='cupon',
        ),
        migrations.RemoveField(
            model_name='historicalcupon',
            name='afiliado',
        ),
        migrations.RemoveField(
            model_name='historicalcupon',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='historicalcupon',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcupon',
            name='mes',
        ),
        migrations.RemoveField(
            model_name='historicalcupon',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Cupon',
        ),
        migrations.DeleteModel(
            name='DetalleCupones',
        ),
        migrations.DeleteModel(
            name='HistoricalCupon',
        ),
    ]
