# Generated by Django 4.2.29 on 2026-07-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0009_remove_detallecupones_concepto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltiposdocumentos',
            name='tipo_electronica',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Factura electrónica'), (2, 'Nota débito'), (3, 'Nota crédito'), (4, 'Documento soporte'), (5, 'Nota ajuste')], null=True),
        ),
        migrations.AlterField(
            model_name='tiposdocumentos',
            name='tipo_electronica',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Factura electrónica'), (2, 'Nota débito'), (3, 'Nota crédito'), (4, 'Documento soporte'), (5, 'Nota ajuste')], null=True),
        ),
    ]
