# Generated by Django 4.2.29 on 2026-07-22 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0009_remove_detallecupones_concepto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiporetencion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tiporetencion',
            name='base_sobre',
            field=models.CharField(choices=[('SUBTOTAL', 'Sobre el subtotal'), ('IVA', 'Sobre el IVA')], default='SUBTOTAL', help_text='Indica si se calcula sobre el subtotal o sobre el IVA', max_length=20),
        ),
        migrations.AddField(
            model_name='tiporetencion',
            name='cuenta_contable',
            field=models.ForeignKey(blank=True, help_text='Cuenta contable de la retención (ej: 2365 ReteFuente)', null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.mayor'),
        ),
        migrations.AddField(
            model_name='tiporetencion',
            name='porcentaje_defecto',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Porcentaje por defecto al asignar a un afiliado (ej: 3.5 para 3.5%)', max_digits=8),
        ),
    ]
