# Generated by Django 4.2.29 on 2026-07-27 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0010_alter_historicaltiposdocumentos_tipo_electronica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagodocumento',
            name='forma_pago_electro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.formapagoelectro'),
        ),
    ]
