# Generated by Django 4.2.29 on 2026-07-27 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0010_tiporetencion_activo_tiporetencion_base_sobre_and_more'),
        ('contabilidad', '0011_pagodocumento_forma_pago_electro'),
    ]

    operations = [
    ]
