# Generated by Django 4.2.29 on 2026-07-31 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contabilidad', '0012_merge_20260727_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('delete', models.DateTimeField(blank=True, default=None, help_text='Date time on which the object was last delete.', null=True, verbose_name='delete at')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('icono', models.CharField(blank=True, default='assignment', max_length=50, null=True)),
                ('color', models.CharField(blank=True, default='primary', max_length=20, null=True)),
                ('requiere_tercero', models.BooleanField(default=True)),
                ('requiere_valor', models.BooleanField(default=True)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantillas', to='contabilidad.concepto')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantillas', to='contabilidad.tiposdocumentos')),
                ('uc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('um', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_update', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cont_plantilla_documento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('delete', models.DateTimeField(blank=True, default=None, help_text='Date time on which the object was last delete.', null=True, verbose_name='delete at')),
                ('naturaleza', models.CharField(choices=[('debito', 'Débito'), ('credito', 'Crédito')], max_length=10)),
                ('tipo_valor', models.CharField(choices=[('fijo', 'Valor fijo'), ('porcentaje', 'Porcentaje del valor principal'), ('formula', 'Fórmula')], default='porcentaje', max_length=20)),
                ('valor_fijo', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('usa_tercero', models.BooleanField(default=True)),
                ('detalle_default', models.CharField(blank=True, max_length=255, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantilla_movimientos', to='contabilidad.concepto')),
                ('mayor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantilla_movimientos', to='contabilidad.mayor')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='contabilidad.plantilladocumento')),
                ('uc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('um', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_update', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cont_plantilla_movimiento',
                'ordering': ['orden'],
            },
        ),
    ]
