# Generated by Django 4.2.29 on 2026-08-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0013_plantilladocumento_plantillamovimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilladocumento',
            name='categoria',
            field=models.CharField(choices=[('General', 'General'), ('Ingresos', 'Ingresos'), ('Egresos', 'Egresos'), ('Notas', 'Notas / Contabilidad'), ('Nomina', 'Nómina')], default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='plantilladocumento',
            name='contador_usos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plantilladocumento',
            name='ultima_fecha_uso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantillamovimiento',
            name='base_minima',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
    ]
