# Generated by Django 4.2.29 on 2026-08-05 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0014_plantilladocumento_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantilladocumento',
            name='categoria',
        ),
        migrations.AddField(
            model_name='plantilladocumento',
            name='fuente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plantillas', to='contabilidad.fuentes'),
        ),
    ]
