# Generated by Django 4.2.29 on 2026-08-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0015_remove_plantilladocumento_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillamovimiento',
            name='origen_valor',
            field=models.CharField(choices=[('VALOR_TOTAL', 'Valor Total Principal'), ('SUBTOTAL', 'Subtotal / Base Gravable'), ('IMPUESTO_IVA', 'Variable: IVA Calculado'), ('RETEFUENTE', 'Variable: Retención en la Fuente'), ('RETEICA', 'Variable: Retención de ICA'), ('RETEIVA', 'Variable: Retención de IVA'), ('NETO_PAGAR', 'Variable: Neto a Pagar (Cierre)'), ('PORCENTAJE_DIRECTO', 'Porcentaje Directo (Manual)'), ('VALOR_FIJO', 'Valor Fijo (Manual)')], default='PORCENTAJE_DIRECTO', max_length=50),
        ),
    ]
