# Generated by Django 4.2.29 on 2026-08-05 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contabilidad', '0016_plantillamovimiento_origen_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('delete', models.DateTimeField(blank=True, default=None, help_text='Date time on which the object was last delete.', null=True, verbose_name='delete at')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo_variable', models.CharField(choices=[('IMPUESTO_IVA', 'IVA Calculado'), ('RETEFUENTE', 'Retención en la Fuente'), ('RETEICA', 'Retención de ICA'), ('RETEIVA', 'Retención de IVA')], max_length=50)),
                ('tarifa_porcentaje', models.DecimalField(decimal_places=4, default=0.0, max_digits=7)),
                ('base_minima', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('vigencia_anio', models.IntegerField(default=2026)),
                ('activa', models.BooleanField(default=True)),
                ('cuenta_contable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reglas_tributarias', to='contabilidad.mayor')),
                ('uc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('um', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_update', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cont_regla_tributaria',
                'ordering': ['tipo_variable', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='plantillamovimiento',
            name='regla_tributaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantilla_movimientos', to='contabilidad.reglatributaria'),
        ),
    ]
