# Generated by Django 4.2.29 on 2026-08-06 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0018_variablecontable_conceptoreglatributaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagotransferencia',
            name='numero_cheque',
        ),
        migrations.AddField(
            model_name='formapago',
            name='codigo',
            field=models.CharField(blank=True, help_text='Slug semántico: EFECTIVO, CONSIGNACION, TARJETA, CHEQUE, TRANSFERENCIA', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='formapago',
            name='forma_pago_electro',
            field=models.ForeignKey(blank=True, help_text='Mapeo al código DIAN de facturación electrónica', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.formapagoelectro'),
        ),
        migrations.AddField(
            model_name='pagotransferencia',
            name='referencia',
            field=models.CharField(blank=True, help_text='Número de transacción o referencia de la transferencia', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='fpago',
            field=models.IntegerField(blank=True, editable=False, help_text='[DEPRECATED] Usar PagoDocumento.forma_pago. Campo conservado por compatibilidad histórica.', null=True),
        ),
        migrations.AlterField(
            model_name='historicaldocumentos',
            name='fpago',
            field=models.IntegerField(blank=True, editable=False, help_text='[DEPRECATED] Usar PagoDocumento.forma_pago. Campo conservado por compatibilidad histórica.', null=True),
        ),
        migrations.AlterField(
            model_name='pagodocumento',
            name='medio_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.mediopagoelectro'),
        ),
    ]
