# Generated by Django 4.2.29 on 2026-08-06 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0019_formapago_codigo_fk_pagotransferencia_referencia_medio_pago_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentos',
            name='fpago',
        ),
        migrations.RemoveField(
            model_name='historicaldocumentos',
            name='fpago',
        ),
        migrations.AlterField(
            model_name='pagocheque',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.banco'),
        ),
        migrations.AlterField(
            model_name='pagocheque',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagocheque',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pagoconsignacion',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.banco'),
        ),
        migrations.AlterField(
            model_name='pagoconsignacion',
            name='cuenta_bancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.cuentabancaria'),
        ),
        migrations.AlterField(
            model_name='pagoconsignacion',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagoconsignacion',
            name='numero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pagoconsignacion',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='pagotarjeta',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.banco'),
        ),
        migrations.AlterField(
            model_name='pagotarjeta',
            name='numero_tarjeta',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='pagotarjeta',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='pagotransferencia',
            name='banco_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.banco'),
        ),
        migrations.AlterField(
            model_name='pagotransferencia',
            name='cuenta_destino',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pagotransferencia',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
