# Generated by Django 4.2.29 on 2026-08-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0020_pagos_detalles_campos_opcionales'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='fpago',
            field=models.IntegerField(blank=True, editable=False, help_text='[DEPRECATED] Usar PagoDocumento.forma_pago. Campo conservado por compatibilidad histórica.', null=True),
        ),
        migrations.AddField(
            model_name='historicaldocumentos',
            name='fpago',
            field=models.IntegerField(blank=True, editable=False, help_text='[DEPRECATED] Usar PagoDocumento.forma_pago. Campo conservado por compatibilidad histórica.', null=True),
        ),
    ]
