# Generated by Django 4.2.29 on 2026-08-06 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0021_restaurar_fpago_documentos_compatibilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagodocumento',
            name='forma_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.formapago'),
        ),
    ]
