# Generated by Django 4.2.29 on 2026-08-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0021_restaurar_fpago_documentos_compatibilidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagodocumento',
            options={},
        ),
        migrations.AddIndex(
            model_name='documentos',
            index=models.Index(fields=['tipo_documento', 'fecha', 'estado'], name='cont_docume_tipo_do_fe33a3_idx'),
        ),
        migrations.AddIndex(
            model_name='documentos',
            index=models.Index(fields=['personas', 'fecha'], name='cont_docume_persona_344b36_idx'),
        ),
        migrations.AddIndex(
            model_name='mov',
            index=models.Index(fields=['documento', 'mayor', 'persona'], name='contabilida_documen_69d96e_idx'),
        ),
        migrations.AddIndex(
            model_name='pagodocumento',
            index=models.Index(fields=['documento', 'forma_pago'], name='contabilida_documen_7e492b_idx'),
        ),
        migrations.AlterModelTable(
            name='mov',
            table='contabilidad_mov',
        ),
    ]
