# Generated by Django 4.2.29 on 2026-08-10 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0022_alter_pagodocumento_forma_pago'),
        ('contabilidad', '0022_alter_pagodocumento_options_and_more'),
    ]

    operations = [
    ]
