# Generated by Django 4.2.29 on 2026-04-13 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortalesSincronizacion',
        ),
    ]
