# Generated by Django 4.2.29 on 2026-04-16 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0002_delete_portalessincronizacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barrio',
            options={},
        ),
        migrations.AlterModelOptions(
            name='zona',
            options={},
        ),
        migrations.AlterModelTable(
            name='barrio',
            table='parametros_ubicacion_barrios',
        ),
        migrations.AlterModelTable(
            name='ciudad',
            table='parametros_ubicacion_ciudades',
        ),
        migrations.AlterModelTable(
            name='zona',
            table='parametros_ubicacion_zonas',
        ),
    ]
