# Generated by Django 4.2.29 on 2026-04-27 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parametros', '0003_alter_barrio_options_alter_zona_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('delete', models.DateTimeField(blank=True, default=None, help_text='Date time on which the object was last delete.', null=True, verbose_name='delete at')),
                ('nombre', models.CharField(help_text='Nombre', max_length=255)),
                ('uc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('um', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_update', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parametros_tipos_vias',
                'ordering': ['-created', '-modified'],
            },
        ),
    ]
