# Generated by Django 4.2.29 on 2026-08-19 20:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0005_aplicativo_tipocontrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_intento', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha y hora del intento')),
                ('fecha_resultado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora del resultado')),
                ('tipo_remitente', models.CharField(choices=[('general', 'Correo general'), ('propietarios', 'Correo propietarios'), ('arrendatarios', 'Correo arrendatarios'), ('comercial', 'Correo comercial'), ('administracion', 'Correo administración'), ('cartera', 'Correo cartera'), ('reparaciones', 'Correo reparaciones'), ('correspondencia', 'Correspondencia (tipo 2)'), ('desconocido', 'Desconocido')], default='desconocido', max_length=20, verbose_name='Tipo de remitente')),
                ('correo_remitente', models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo remitente usado')),
                ('destinatarios', models.TextField(verbose_name='Destinatarios (separados por coma)')),
                ('total_destinatarios', models.PositiveSmallIntegerField(default=0, verbose_name='Cantidad de destinatarios')),
                ('asunto', models.TextField(verbose_name='Asunto')),
                ('plantilla', models.TextField(blank=True, default='', verbose_name='Plantilla usada')),
                ('estado', models.CharField(choices=[('exitoso', 'Exitoso'), ('fallido', 'Fallido'), ('pendiente', 'Pendiente')], db_index=True, default='pendiente', max_length=25, verbose_name='Estado del envío')),
                ('categoria_error', models.CharField(blank=True, choices=[('destinatario', 'Dirección del destinatario'), ('remitente', 'Credenciales / cuenta remitente'), ('smtp', 'Conexión SMTP'), ('adjunto', 'Adjunto inválido o no encontrado'), ('plantilla', 'Error en la plantilla de correo'), ('configuracion', 'Configuración faltante o incorrecta'), ('tracking', 'Configuración de tracking inválida'), ('desconocido', 'Error desconocido')], db_index=True, default='', max_length=25, verbose_name='Categoría del error')),
                ('mensaje_error', models.TextField(blank=True, default='', verbose_name='Mensaje de error detallado')),
                ('traceback_error', models.TextField(blank=True, default='', verbose_name='Traceback completo')),
                ('smtp_host', models.CharField(blank=True, default='', max_length=255, verbose_name='Host SMTP')),
                ('smtp_port', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Puerto SMTP')),
                ('usando_tracking', models.BooleanField(default=False, verbose_name='Usó cuenta de tracking')),
                ('tiene_adjuntos', models.BooleanField(default=False, verbose_name='Tenía adjuntos')),
                ('total_adjuntos', models.PositiveSmallIntegerField(default=0, verbose_name='Total de adjuntos')),
            ],
            options={
                'verbose_name': 'Log de correo',
                'verbose_name_plural': 'Logs de correos',
                'db_table': 'email_log',
                'ordering': ['-fecha_intento'],
            },
        ),
        migrations.CreateModel(
            name='EmailLogAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512, verbose_name='Nombre del archivo')),
                ('ruta', models.CharField(blank=True, default='', max_length=1024, verbose_name='Ruta en disco (si aplica)')),
                ('desde_memoria', models.BooleanField(default=False, verbose_name='Adjunto desde memoria (bytes)')),
                ('mimetype', models.CharField(blank=True, default='', max_length=128, verbose_name='MIME type')),
                ('existe', models.BooleanField(default=True, verbose_name='El archivo existía al momento del envío')),
                ('email_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='parametros.emaillog', verbose_name='Log de correo')),
            ],
            options={
                'verbose_name': 'Adjunto de log',
                'verbose_name_plural': 'Adjuntos de log',
                'db_table': 'email_log_adjunto',
            },
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['estado', 'fecha_intento'], name='email_log_estado_45b9d5_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['categoria_error', 'fecha_intento'], name='email_log_categor_eb854c_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['tipo_remitente', 'fecha_intento'], name='email_log_tipo_re_93747d_idx'),
        ),
    ]
