# Generated by Django 4.2.29 on 2026-08-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entidad',
            old_name='tipo_entidades',
            new_name='tipo_entidad',
        ),
        migrations.RenameField(
            model_name='entidadcentrocosto',
            old_name='entidades',
            new_name='entidad',
        ),
        migrations.RenameField(
            model_name='historicalentidad',
            old_name='tipo_entidades',
            new_name='tipo_entidad',
        ),
        migrations.RenameField(
            model_name='historicalentidadcentrocosto',
            old_name='entidades',
            new_name='entidad',
        ),
        migrations.AlterField(
            model_name='entidad',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='historicalentidad',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
