# Generated by Django 4.2.29 on 2026-08-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0003_historicalcargo_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NominaParametros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.TextField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('grupo', models.CharField(blank=True, help_text='Agrupar los parametros', max_length=30, null=True)),
                ('orden', models.IntegerField(blank=True, help_text='Orden a mostrar', null=True)),
                ('comentario', models.TextField(blank=True, help_text='Comentario para indicar algo del parametro', null=True)),
            ],
            options={
                'db_table': 'nomina_parametros',
            },
        ),
    ]
