# Generated by Django 4.2.29 on 2026-08-13 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0023_merge_20260810_1121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nomina', '0005_contratonomina_contratonominanovedades_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDatosPago',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(blank=True, editable=False, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('delete', models.DateTimeField(blank=True, default=None, help_text='Date time on which the object was last delete.', null=True, verbose_name='delete at')),
                ('numero_cuenta', models.CharField(max_length=30)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('banco', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contabilidad.banco')),
                ('contrato', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nomina.contratonomina')),
                ('forma_pago', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contabilidad.formapagoelectro')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('medio_pago', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contabilidad.mediopagoelectro')),
                ('tipo_cuenta', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contabilidad.tipocuenta')),
                ('uc', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('um', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical datos pago',
                'verbose_name_plural': 'historical datos pagos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDatosAportes',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(blank=True, editable=False, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('delete', models.DateTimeField(blank=True, default=None, help_text='Date time on which the object was last delete.', null=True, verbose_name='delete at')),
                ('porcentaje_salud', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('porcentaje_pension', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('porcentaje_arl', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('arl', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nomina.entidad')),
                ('caja_compensacion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nomina.entidad')),
                ('contrato', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nomina.contratonomina')),
                ('entidad_pension', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nomina.entidad')),
                ('entidad_salud', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nomina.entidad')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('nivel_riesgo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nomina.nivelriesgo')),
                ('uc', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('um', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical datos aportes',
                'verbose_name_plural': 'historical datos aportess',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
