# Generated by Django 4.2.29 on 2026-08-18 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parametros', '0005_aplicativo_tipocontrato'),
        ('contabilidad', '0023_merge_20260810_1121'),
        ('nomina', '0006_historicaldatospago_historicaldatosaportes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidacionNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('delete', models.DateTimeField(blank=True, default=None, help_text='Date time on which the object was last delete.', null=True, verbose_name='delete at')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('dias_laborados', models.IntegerField(blank=True, null=True)),
                ('sueldo_trabajado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('auxilio_transporte', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('otros_devengados', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('salud', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pension', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('otros_deducidos', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('fecha_inicial', models.DateField()),
                ('fecha_final', models.DateField()),
                ('contabilizado', models.BooleanField(default=False)),
                ('pago', models.BooleanField(default=False)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidacion_nomina_anio', to='parametros.anio')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidacion_nomina_contrato', to='nomina.contratonomina')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liquidacion_documento', to='contabilidad.documentos')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidacion_nomina_mes', to='parametros.mes')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidacion_nomina_periodo', to='nomina.periodo')),
                ('uc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('um', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_update', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('usuario_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liquidacion_user_pago', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nomina_liquidaciones',
            },
        ),
        migrations.CreateModel(
            name='DetalleLiquidacionNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('delete', models.DateTimeField(blank=True, default=None, help_text='Date time on which the object was last delete.', null=True, verbose_name='delete at')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('valor_empleado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('valor_patrono', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('fecha_inicial', models.DateTimeField()),
                ('fecha_final', models.DateTimeField()),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_liquidacion_nomina_liquidacion', to='nomina.liquidacionnomina')),
                ('novedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_liquidacion_nomina_novedad', to='nomina.novedad')),
                ('uc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('um', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_update', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nomina_detalle_liquidaciones',
            },
        ),
    ]
