# Generated by Django 4.2.29 on 2026-08-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0007_liquidacionnomina_detalleliquidacionnomina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacionnomina',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
