# Generated by Django 4.2.29 on 2026-08-18 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nomina', '0008_alter_liquidacionnomina_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('delete', models.DateTimeField(blank=True, default=None, help_text='Date time on which the object was last delete.', null=True, verbose_name='delete at')),
                ('dias', models.IntegerField()),
                ('sueldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('valor_dia', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('salud_valor_porcentaje', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('salud_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pension_valor_porcentaje', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pension_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacaciones_contrato', to='nomina.contratonomina')),
                ('contrato_novedades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacaciones_contrato_novedades', to='nomina.contratonominanovedades')),
                ('uc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('um', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_update', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nomina_vacaciones',
            },
        ),
    ]
