# Generated by Django 4.2.29 on 2026-08-20 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0023_merge_20260810_1121'),
        ('parametros', '0006_emaillog_emaillogadjunto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nomina', '0009_vacaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='NominaElectronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('delete', models.DateTimeField(blank=True, default=None, help_text='Date time on which the object was last delete.', null=True, verbose_name='delete at')),
                ('fecha_ini_liquidacion', models.DateField()),
                ('fecha_fin_liquidacion', models.DateField()),
                ('dias_laborados', models.IntegerField()),
                ('tipo_nomina', models.IntegerField()),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('prefijo', models.CharField(blank=True, max_length=50, null=True)),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('data_funcionalidad', models.TextField(blank=True, null=True)),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomina_electronica_anio', to='parametros.anio')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomina_electronica_contrato', to='nomina.contratonomina')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.estadofactelectro')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomina_electronica_mes', to='parametros.mes')),
                ('uc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('um', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_update', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NominaElectronicaValores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sueldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sueldo_trabajado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('auxilio_transporte', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('viaticos_salarriales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('viaticos_nosalariales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('otros_devengados', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_devengados', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('salud', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pension', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('fondo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('arl', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('otros_deducidos', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_deducido', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('nomina_electronica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nomina_electronica_valores', to='nomina.nominaelectronica')),
            ],
        ),
        migrations.CreateModel(
            name='NominaElectronicaLiquidaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidacion_nomina_electronica', to='nomina.liquidacionnomina')),
                ('nomina_electronica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomina_electronica_nomina_electronica', to='nomina.nominaelectronica')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleNominaElectronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('patrono', models.BooleanField(default=False)),
                ('provisional', models.BooleanField(blank=True, default=False, null=True)),
                ('fecha_ini', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('nomina_electronica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_nomina_electronica', to='nomina.nominaelectronica')),
                ('novedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='novedades_detalle_nomina_electronica', to='nomina.novedad')),
            ],
        ),
    ]
