# Generated by Django 4.2.29 on 2026-08-20 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0010_nominaelectronica_nominaelectronicavalores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosaportes',
            name='contrato',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_aportes_contrato_nomina', to='nomina.contratonomina'),
        ),
        migrations.AlterField(
            model_name='datospago',
            name='contrato',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_pago_contrato_nomina', to='nomina.contratonomina'),
        ),
    ]
