# Generated by Django 4.2.29 on 2026-06-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliadoconceptocausacion',
            name='detalle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalafiliadoconceptocausacion',
            name='detalle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
