# Generated by Django 4.2.29 on 2026-06-25 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0002_afiliadoconceptocausacion_detalle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliadoconceptocausacion',
            name='afiliado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afiliado_concepto_causacion', to='afiliados.afiliado'),
        ),
        migrations.AlterField(
            model_name='afiliadoconceptocausacion',
            name='concepto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepto_concepto_causacion', to='afiliados.conceptocausacion'),
        ),
    ]
