# Generated by Django 4.2.29 on 2026-06-27 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_remove_documentos_mandato_and_more'),
        ('afiliados', '0003_alter_afiliadoconceptocausacion_afiliado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliado',
            name='porc_avisos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='afiliado',
            name='porc_bomberil',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='afiliado',
            name='porc_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='afiliado',
            name='porc_rte_fte',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='afiliado',
            name='porc_rte_ica',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='afiliado',
            name='porc_rte_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptocausacion',
            name='cta_iva',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_iva_concepto', to='contabilidad.mayor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalafiliado',
            name='porc_avisos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalafiliado',
            name='porc_bomberil',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalafiliado',
            name='porc_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalafiliado',
            name='porc_rte_fte',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalafiliado',
            name='porc_rte_ica',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalafiliado',
            name='porc_rte_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalconceptocausacion',
            name='cta_iva',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contabilidad.mayor'),
        ),
    ]
