# Generated by Django 4.2.29 on 2026-06-30 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_remove_documentos_mandato_and_more'),
        ('afiliados', '0003_alter_afiliadoconceptocausacion_afiliado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliadoconceptocausacion',
            name='porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='conceptocausacion',
            name='cta_iva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_iva_concepto', to='contabilidad.mayor'),
        ),
        migrations.AddField(
            model_name='historicalafiliadoconceptocausacion',
            name='porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='historicalconceptocausacion',
            name='cta_iva',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contabilidad.mayor'),
        ),
    ]
