# Generated by Django 4.2.29 on 2026-06-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0004_afiliadoconceptocausacion_porcentaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptocausacion',
            name='es_retencion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalconceptocausacion',
            name='es_retencion',
            field=models.BooleanField(default=False),
        ),
    ]
