# Generated by Django 4.2.29 on 2026-07-01 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_remove_documentos_mandato_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('afiliados', '0005_conceptocausacion_es_retencion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturacionAfiliados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('delete', models.DateTimeField(blank=True, default=None, help_text='Date time on which the object was last delete.', null=True, verbose_name='delete at')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afiliado_facturacion', to='afiliados.afiliado')),
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='afiliado_documento', to='contabilidad.documentos')),
                ('uc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('um', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_update', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalFacturacionDetalleAfiliados',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(blank=True, editable=False, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('delete', models.DateTimeField(blank=True, default=None, help_text='Date time on which the object was last delete.', null=True, verbose_name='delete at')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('concepto_causacion_afiliado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='afiliados.afiliadoconceptocausacion')),
                ('facturacion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='afiliados.facturacionafiliados')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uc', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('um', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical facturacion detalle afiliados',
                'verbose_name_plural': 'historical facturacion detalle afiliadoss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFacturacionAfiliados',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(blank=True, editable=False, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('delete', models.DateTimeField(blank=True, default=None, help_text='Date time on which the object was last delete.', null=True, verbose_name='delete at')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('afiliado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='afiliados.afiliado')),
                ('documento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contabilidad.documentos')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uc', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('um', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical facturacion afiliados',
                'verbose_name_plural': 'historical facturacion afiliadoss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FacturacionDetalleAfiliados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('delete', models.DateTimeField(blank=True, default=None, help_text='Date time on which the object was last delete.', null=True, verbose_name='delete at')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18)),
                ('concepto_causacion_afiliado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='afiliado_concepto_causacion', to='afiliados.afiliadoconceptocausacion')),
                ('facturacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afiliado_facturacion', to='afiliados.facturacionafiliados')),
                ('uc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('um', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_update', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
