# Generated by Django 4.2.29 on 2026-07-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0005_conceptocausacion_es_retencion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliadoconceptocausacion',
            name='facturar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalafiliadoconceptocausacion',
            name='facturar',
            field=models.BooleanField(default=False),
        ),
    ]
