# Generated by Django 4.2.29 on 2026-07-01 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0007_tiporetencion'),
        ('afiliados', '0005_conceptocausacion_es_retencion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conceptocausacion',
            name='es_retencion',
        ),
        migrations.RemoveField(
            model_name='historicalconceptocausacion',
            name='es_retencion',
        ),
        migrations.AddField(
            model_name='conceptocausacion',
            name='tipo_retencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.tiporetencion'),
        ),
        migrations.AddField(
            model_name='historicalconceptocausacion',
            name='tipo_retencion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contabilidad.tiporetencion'),
        ),
    ]
