# Generated by Django 4.2.29 on 2026-07-01 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0006_facturacionafiliados_and_more'),
        ('afiliados', '0006_remove_conceptocausacion_es_retencion_and_more'),
    ]

    operations = [
    ]
