# Generated by Django 4.2.29 on 2026-07-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0007_merge_20260701_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptocausacion',
            name='es_retencion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalconceptocausacion',
            name='es_retencion',
            field=models.BooleanField(default=False),
        ),
    ]
