# Generated by Django 4.2.29 on 2026-07-01 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0008_conceptocausacion_es_retencion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaciondetalleafiliados',
            name='concepto_causacion_afiliado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afiliado_concepto_causacion', to='afiliados.afiliadoconceptocausacion'),
        ),
    ]
