# Generated by Django 4.2.29 on 2026-07-02 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0006_afiliadoconceptocausacion_facturar_and_more'),
        ('afiliados', '0009_alter_facturaciondetalleafiliados_concepto_causacion_afiliado'),
    ]

    operations = [
    ]
