# Generated by Django 4.2.29 on 2026-07-17 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0011_cupon_historicalcupon_detallecupones'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecupones',
            name='concepto_causacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='afiliados.conceptocausacion'),
        ),
    ]
