# Generated by Django 4.2.29 on 2026-07-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0010_tiporetencion_activo_tiporetencion_base_sobre_and_more'),
        ('afiliados', '0012_detallecupones_concepto_causacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptocausacion',
            name='retenciones',
            field=models.ManyToManyField(blank=True, help_text='Retenciones que aplican sobre este concepto (solo para conceptos NO retención)', related_name='conceptos_gravables', to='contabilidad.tiporetencion'),
        ),
    ]
