# Generated by Django 4.2.29 on 2026-06-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedimientoSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del procedimiento', max_length=50)),
                ('hash', models.CharField(help_text='Hash del procedimiento (para validar si es el mismo o si se cambió)', max_length=64)),
                ('fecha_sync', models.DateTimeField()),
            ],
            options={
                'db_table': 'procedimientos_sync',
            },
        ),
    ]
