# Generated by Django 4.2.29 on 2026-06-27 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_procedimientosync'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permisosmenuacciones',
            name='grupo',
        ),
    ]
