# Generated by Django 4.2.29 on 2026-06-30 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_remove_permisosmenuacciones_grupo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['orden']},
        ),
        migrations.RemoveField(
            model_name='permisosmenuacciones',
            name='permiso_accion',
        ),
        migrations.RemoveField(
            model_name='permisosmenuacciones',
            name='permiso_menu',
        ),
        migrations.AddField(
            model_name='permisosmenuacciones',
            name='permiso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_acciones_permiso', to='public.menu'),
        ),
    ]
