# Generated by Django 4.2.29 on 2026-06-30 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('public', '0004_alter_menu_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisosmenuacciones',
            name='permiso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_acciones_permiso', to='auth.permission'),
        ),
    ]
