# Generated by Django 4.2.29 on 2026-06-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_alter_permisosmenuacciones_permiso'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='codigo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
