from django.db import models
from .cuenta import Mayor
from apps.personas.models.persona import Persona

class Saldos(models.Model):
    anio = models.IntegerField(blank=True, null=True)
    mayor = models.ForeignKey(Mayor, on_delete=models.CASCADE)
    sali = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True) 
    d01 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)  
    h01 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)  
    sal01 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    d02 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)  
    h02 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)  
    sal02 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    d03 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    h03 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    sal03 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    d04 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    h04 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    sal04 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    d05 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    h05 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    sal05 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    d06 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    h06 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    sal06 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    d07 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    h07 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    sal07 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    d08 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    h08 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    sal08 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    d09 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    h09 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    sal09 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    d10 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    h10 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    sal10 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    d11 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    h11 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    sal11 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    d12 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    h12 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    sal12 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    d13 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    h13 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    sal13 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    cont_mayor_niif_id = models.IntegerField()

class SaldosNits(models.Model):
    anio = models.IntegerField(blank=True, null=True)
    sali = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    d01 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    h01 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    sal01 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    d02 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    h02 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    sal02 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    d03 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    h03 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    sal03 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    d04 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    h04 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    sal04 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    d05 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    h05 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    sal05 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    d06 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    h06 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    sal06 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    d07 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    h07 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    sal07 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    d08 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    h08 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    sal08 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    d09 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    h09 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    sal09 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    d10 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    h10 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    sal10 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    d11 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    h11 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    sal11 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    d12 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    h12 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    sal12 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    d13 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    h13 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    sal13 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    personas = models.ForeignKey(Persona, models.DO_NOTHING)
    mayor = models.ForeignKey(Mayor, models.DO_NOTHING)
