# Generated by Django 4.2.29 on 2026-08-20 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpersona',
            name='estado',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personas.estadopersona'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='estado',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_persona', to='personas.estadopersona'),
        ),
    ]
